version: "3"

services:
  colyseus-service:
    container_name: colyseus-service
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      DB_MONGODB_URI: mongodb://root:example@localhost:27017/nekorooms
      DB_REDIS_PORT: 6379
    depends_on:
      - mongodb
      - postgre
      - redis
  mongodb:
    image: mongo:3.0
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongodb:/data/configdb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: nekorooms
  postgre:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgre:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: neko
      POSTGRES_USER: kewin
      POSTGRES_PASSWORD: 1234567
    ports:
      - 5432:5432

  redis:
    image: redis:3.2-alpine
    container_name: redis_db
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - redis:/data/
    restart: always
volumes:
  mongodb:
  redis:
  postgre:

